language: kotlin

before_install:
  - |
    if ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(.md)|(.html)|^(LICENSE)|^(docs)'
    then
      echo "Only docs were updated, not running the CI."
      exit
    fi
  - ./gradlew --no-daemon build

script: ./gradlew --no-daemon test

notifications:
  email: false
